version: '3.8'
services:
  csv-to-postgres:
    build:
      context: .
      target: development
    ports:
      - "9229:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
