version: '3.8'
services:
  csv-to-postgres:
    build:
      context: .
      target: production
    image: csv-to-postgres
    container_name: csv-to-postgres
    volumes:
      - ./input:/home/node/input
      - ./output:/home/node/output
    environment:
      NODE_OPTIONS: "--max-old-space-size=8192"
